language: php
php:
  - "7.1"

install:
  composer install

script:
 - ./vendor/bin/phpunit --configuration tests/phpunit.xml --bootstrap tests/Bootstrap.php
 - ./vendor/bin/phpcs --standard=psr2 src/
 - ./vendor/bin/phpcs --standard=psr2 tests/
